server:
  port: 8081
zzp:
  name: 刘建华开发环境
  age: 27
  height: 170cm
  weight: 74kg

rand:
  str: ${random.value} #32位随机字符串
  uuid: ${random.uuid} #uuid
  num: ${random.int(100)} #100内随机整数
  num0: ${random.int(0,99)} #0-99内随机整数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource